# configs/paths.yaml

data_dir: "data"
models_dir: "models"
reports_dir: "reports"
logs_dir: "logs"
src_dir: "src"
sql_dir: "sql"

raw_dir: "${data_dir}/raw"
processed_dir: "${data_dir}/processed"
features_dir: "${data_dir}/features"

data_file_name: "data.csv"  #placeholder

# --- Имена таблиц в СУБД ---
table_name: "v_session_features"  # Имя итоговой витрины/представления, которую будет читать модель
raw_sessions_table: "ga_sessions"
raw_hits_table: "ga_hits"

# --- Сырые файлы для первоначальной загрузки ---
raw_sessions_file: "ga_sessions.csv"
raw_hits_file: "ga_hits.csv"